services:
  - type: web
    name: blog-site
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        generateValue: true
